# deploy Maven artifacts to Sonatype OSS repo
language: java

jdk:
  - openjdk6

# whitelist
branches:
  only:
    - master
    - wicket-1.4
    - wicket-1.5

# checkout settings
before_install: 
  - "git clone -b master https://github.com/molindo/travis-settings.git target/travis-settings"
  - "target/travis-settings/tasks/before_install.sh"

# install and deploy
install: "target/travis-settings/tasks/install.sh"
script:  "target/travis-settings/tasks/script.sh"

# travis encrypt 'token@room'
notifications:
  email: false
  hipchat: 
    rooms:
      - secure: "WFGsSbTxQKFRNHBoqNNuMyW64rVeCzlOJypB3zvN4gxF1eW3P7KwN+zqhJzUFPHHlvZrU3Col7KvX6xHr8UkY7r/GJYk/0MOJqO5kFdanOiBQtwYDPsfALmSS0wIOsfHTgANMTiOAuC9txGZD3SSdDA9qSsQOY4k8bHqw59F8Ac="
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Change view</a>)'
    format: html
    on_success: always
    on_failure: always

# travis encrypt 'CI_DEPLOY_USERNAME=username'
# travis encrypt 'CI_DEPLOY_PASSWORD=password'
env:
  global:
    - secure: "POc9lKllPgr+fpdWk4TqTDmWSIyKMMFEkGBOMxXDU38Vr3/WSg7k0I1bccP8VBdRCyLLWY42TZNT51NOyquc42sygaL6v2Yo5LSlo4eMFv6A5XajOX7yJioXqHbt0iAv5FoyKxGSYZPNBmeglrtPR40tN2MTHSt8kLpZfRUZT6M="
    - secure: "hSGH+V5fZKaPyNubZd8dRUZIDHZhEOEboC9DVGZlFgT5BR1Z3zH0RN1d7waYlz2vdauMdUP+P1WmWBzQpS5pR5TKTcIqWKjCL3SVzoM+7KN/OXwe0iYLGhikC3Dz4NdSQ1wjSvnRHX3xn5KiKx7Z0XDT77GM+7GdVrETDD6nUrs="
